import Head from "next/head";
import Layout from "../components/layout";
import ProjectItem from "../components/projects/project-item";
import { DATABASE_ID, TOKEN } from "../config/index";

export default function Projects({ projects }) {
  console.log(projects);
  return (
    <Layout>
      <div className="flex flex-col items-center justify-center min-h-screen px-3 mb-10 w-full">
        <Head>
          <title>Next Web Practice</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className="text-4xl font-bold sm:text-6xl">
          총 프로젝트 :{" "}
          <span className="pl-4 text-blue-500">{projects.length}</span>{" "}
        </h1>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 m-6 py-10 w-full">
          {projects.map((project) => (
            <ProjectItem data={project} key={project.id} />
          ))}
        </div>
      </div>
    </Layout>
  );
}

// 빌드 타임에 호출
export async function getStaticProps() {
  const options = {
    method: "POST",
    headers: {
      accept: "application/json",
      "Notion-Version": "2022-02-22",
      "content-type": "application/json",
      Authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({
      page_size: 100,
    }),
  };

  const responce = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID}/query`,
    options
  );

  // 파싱 과정
  // const projects = await responce.json();
  // const projectsInfos = projects.results.map(
  //   (project) => project.properties["이름"].title[0]
  // );
  // const projectNames = projectsInfos.map((info) => info?.plain_text);

  const projects = await responce.json().then((res) => res.results);

  return {
    props: { projects }, // will be passed to the page component as props
    revalidate: 1,
  };
}
